// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "steammessages.pb.h"

@class CGCMsgGetIPLocation;
@class CGCMsgGetIPLocationResponse;
@class CGCMsgGetIPLocationResponse_Builder;
@class CGCMsgGetIPLocation_Builder;
@class CGCMsgGetSystemStats;
@class CGCMsgGetSystemStatsResponse;
@class CGCMsgGetSystemStatsResponse_Builder;
@class CGCMsgGetSystemStats_Builder;
@class CGCMsgMemCachedDelete;
@class CGCMsgMemCachedDelete_Builder;
@class CGCMsgMemCachedGet;
@class CGCMsgMemCachedGetResponse;
@class CGCMsgMemCachedGetResponse_Builder;
@class CGCMsgMemCachedGetResponse_ValueTag;
@class CGCMsgMemCachedGetResponse_ValueTag_Builder;
@class CGCMsgMemCachedGet_Builder;
@class CGCMsgMemCachedSet;
@class CGCMsgMemCachedSet_Builder;
@class CGCMsgMemCachedSet_KeyPair;
@class CGCMsgMemCachedSet_KeyPair_Builder;
@class CGCMsgSystemStatsSchema;
@class CGCMsgSystemStatsSchema_Builder;
@class CGCSystemMsg_GetAccountDetails;
@class CGCSystemMsg_GetAccountDetails_Builder;
@class CGCSystemMsg_GetAccountDetails_Response;
@class CGCSystemMsg_GetAccountDetails_Response_Builder;
@class CIPLocationInfo;
@class CIPLocationInfo_Builder;
@class CMsgAMAddFreeLicense;
@class CMsgAMAddFreeLicenseResponse;
@class CMsgAMAddFreeLicenseResponse_Builder;
@class CMsgAMAddFreeLicense_Builder;
@class CMsgAMFindAccounts;
@class CMsgAMFindAccountsResponse;
@class CMsgAMFindAccountsResponse_Builder;
@class CMsgAMFindAccounts_Builder;
@class CMsgAMGetLicenses;
@class CMsgAMGetLicensesResponse;
@class CMsgAMGetLicensesResponse_Builder;
@class CMsgAMGetLicenses_Builder;
@class CMsgAMGetUserGameStats;
@class CMsgAMGetUserGameStatsResponse;
@class CMsgAMGetUserGameStatsResponse_Achievement_Blocks;
@class CMsgAMGetUserGameStatsResponse_Achievement_Blocks_Builder;
@class CMsgAMGetUserGameStatsResponse_Builder;
@class CMsgAMGetUserGameStatsResponse_Stats;
@class CMsgAMGetUserGameStatsResponse_Stats_Builder;
@class CMsgAMGetUserGameStats_Builder;
@class CMsgAMGrantGuestPasses2;
@class CMsgAMGrantGuestPasses2Response;
@class CMsgAMGrantGuestPasses2Response_Builder;
@class CMsgAMGrantGuestPasses2_Builder;
@class CMsgAMSendEmail;
@class CMsgAMSendEmailResponse;
@class CMsgAMSendEmailResponse_Builder;
@class CMsgAMSendEmail_Builder;
@class CMsgAMSendEmail_PersonaNameReplacementToken;
@class CMsgAMSendEmail_PersonaNameReplacementToken_Builder;
@class CMsgAMSendEmail_ReplacementToken;
@class CMsgAMSendEmail_ReplacementToken_Builder;
@class CMsgGCGetCommandList;
@class CMsgGCGetCommandListResponse;
@class CMsgGCGetCommandListResponse_Builder;
@class CMsgGCGetCommandList_Builder;
@class CMsgGCGetEmailTemplate;
@class CMsgGCGetEmailTemplateResponse;
@class CMsgGCGetEmailTemplateResponse_Builder;
@class CMsgGCGetEmailTemplate_Builder;
@class CMsgGCGetPersonaNames;
@class CMsgGCGetPersonaNames_Builder;
@class CMsgGCGetPersonaNames_Response;
@class CMsgGCGetPersonaNames_Response_Builder;
@class CMsgGCGetPersonaNames_Response_PersonaName;
@class CMsgGCGetPersonaNames_Response_PersonaName_Builder;
@class CMsgGCMsgMasterSetDirectory;
@class CMsgGCMsgMasterSetDirectory_Builder;
@class CMsgGCMsgMasterSetDirectory_Response;
@class CMsgGCMsgMasterSetDirectory_Response_Builder;
@class CMsgGCMsgMasterSetDirectory_SubGC;
@class CMsgGCMsgMasterSetDirectory_SubGC_Builder;
@class CMsgHttpRequest;
@class CMsgHttpRequest_Builder;
@class CMsgHttpRequest_QueryParam;
@class CMsgHttpRequest_QueryParam_Builder;
@class CMsgHttpRequest_RequestHeader;
@class CMsgHttpRequest_RequestHeader_Builder;
@class CMsgHttpResponse;
@class CMsgHttpResponse_Builder;
@class CMsgHttpResponse_ResponseHeader;
@class CMsgHttpResponse_ResponseHeader_Builder;
@class CMsgNotifyWatchdog;
@class CMsgNotifyWatchdog_Builder;
@class CMsgPackageLicense;
@class CMsgPackageLicense_Builder;
@class CMsgProtoBufHeader;
@class CMsgProtoBufHeader_Builder;
@class CMsgWebAPIKey;
@class CMsgWebAPIKey_Builder;
@class CMsgWebAPIRequest;
@class CMsgWebAPIRequest_Builder;
@class PBDescriptorProto;
@class PBDescriptorProto_Builder;
@class PBDescriptorProto_ExtensionRange;
@class PBDescriptorProto_ExtensionRange_Builder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProto_Builder;
@class PBEnumOptions;
@class PBEnumOptions_Builder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProto_Builder;
@class PBEnumValueOptions;
@class PBEnumValueOptions_Builder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProto_Builder;
@class PBFieldOptions;
@class PBFieldOptions_Builder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProto_Builder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSet_Builder;
@class PBFileOptions;
@class PBFileOptions_Builder;
@class PBMessageOptions;
@class PBMessageOptions_Builder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProto_Builder;
@class PBMethodOptions;
@class PBMethodOptions_Builder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProto_Builder;
@class PBServiceOptions;
@class PBServiceOptions_Builder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfo_Builder;
@class PBSourceCodeInfo_Location;
@class PBSourceCodeInfo_Location_Builder;
@class PBUninterpretedOption;
@class PBUninterpretedOption_Builder;
@class PBUninterpretedOption_NamePart;
@class PBUninterpretedOption_NamePart_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  EGCItemMsgk_EMsgGCBase = 1000,
  EGCItemMsgk_EMsgGCSetItemPosition = 1001,
  EGCItemMsgk_EMsgGCCraft = 1002,
  EGCItemMsgk_EMsgGCCraftResponse = 1003,
  EGCItemMsgk_EMsgGCDelete = 1004,
  EGCItemMsgk_EMsgGCVerifyCacheSubscription = 1005,
  EGCItemMsgk_EMsgGCNameItem = 1006,
  EGCItemMsgk_EMsgGCUnlockCrate = 1007,
  EGCItemMsgk_EMsgGCUnlockCrateResponse = 1008,
  EGCItemMsgk_EMsgGCPaintItem = 1009,
  EGCItemMsgk_EMsgGCPaintItemResponse = 1010,
  EGCItemMsgk_EMsgGCGoldenWrenchBroadcast = 1011,
  EGCItemMsgk_EMsgGCMOTDRequest = 1012,
  EGCItemMsgk_EMsgGCMOTDRequestResponse = 1013,
  EGCItemMsgk_EMsgGCAddItemToSocket_DEPRECATED = 1014,
  EGCItemMsgk_EMsgGCAddItemToSocketResponse_DEPRECATED = 1015,
  EGCItemMsgk_EMsgGCAddSocketToBaseItem_DEPRECATED = 1016,
  EGCItemMsgk_EMsgGCAddSocketToItem_DEPRECATED = 1017,
  EGCItemMsgk_EMsgGCAddSocketToItemResponse_DEPRECATED = 1018,
  EGCItemMsgk_EMsgGCNameBaseItem = 1019,
  EGCItemMsgk_EMsgGCNameBaseItemResponse = 1020,
  EGCItemMsgk_EMsgGCRemoveSocketItem_DEPRECATED = 1021,
  EGCItemMsgk_EMsgGCRemoveSocketItemResponse_DEPRECATED = 1022,
  EGCItemMsgk_EMsgGCCustomizeItemTexture = 1023,
  EGCItemMsgk_EMsgGCCustomizeItemTextureResponse = 1024,
  EGCItemMsgk_EMsgGCUseItemRequest = 1025,
  EGCItemMsgk_EMsgGCUseItemResponse = 1026,
  EGCItemMsgk_EMsgGCGiftedItems = 1027,
  EGCItemMsgk_EMsgGCSpawnItem_DEPRECATED = 1028,
  EGCItemMsgk_EMsgGCRespawnPostLoadoutChange = 1029,
  EGCItemMsgk_EMsgGCRemoveItemName = 1030,
  EGCItemMsgk_EMsgGCRemoveItemPaint = 1031,
  EGCItemMsgk_EMsgGCGiftWrapItem = 1032,
  EGCItemMsgk_EMsgGCGiftWrapItemResponse = 1033,
  EGCItemMsgk_EMsgGCDeliverGift = 1034,
  EGCItemMsgk_EMsgGCDeliverGiftResponseGiver = 1035,
  EGCItemMsgk_EMsgGCDeliverGiftResponseReceiver = 1036,
  EGCItemMsgk_EMsgGCUnwrapGiftRequest = 1037,
  EGCItemMsgk_EMsgGCUnwrapGiftResponse = 1038,
  EGCItemMsgk_EMsgGCSetItemStyle = 1039,
  EGCItemMsgk_EMsgGCUsedClaimCodeItem = 1040,
  EGCItemMsgk_EMsgGCSortItems = 1041,
  EGCItemMsgk_EMsgGC_RevolvingLootList_DEPRECATED = 1042,
  EGCItemMsgk_EMsgGCLookupAccount = 1043,
  EGCItemMsgk_EMsgGCLookupAccountResponse = 1044,
  EGCItemMsgk_EMsgGCLookupAccountName = 1045,
  EGCItemMsgk_EMsgGCLookupAccountNameResponse = 1046,
  EGCItemMsgk_EMsgGCUpdateItemSchema = 1049,
  EGCItemMsgk_EMsgGCRequestInventoryRefresh = 1050,
  EGCItemMsgk_EMsgGCRemoveCustomTexture = 1051,
  EGCItemMsgk_EMsgGCRemoveCustomTextureResponse = 1052,
  EGCItemMsgk_EMsgGCRemoveMakersMark = 1053,
  EGCItemMsgk_EMsgGCRemoveMakersMarkResponse = 1054,
  EGCItemMsgk_EMsgGCRemoveUniqueCraftIndex = 1055,
  EGCItemMsgk_EMsgGCRemoveUniqueCraftIndexResponse = 1056,
  EGCItemMsgk_EMsgGCSaxxyBroadcast = 1057,
  EGCItemMsgk_EMsgGCBackpackSortFinished = 1058,
  EGCItemMsgk_EMsgGCAdjustItemEquippedState = 1059,
  EGCItemMsgk_EMsgGCCollectItem = 1061,
  EGCItemMsgk_EMsgGCItemAcknowledged = 1062,
  EGCItemMsgk_EMsgGCPresets_SelectPresetForClass = 1063,
  EGCItemMsgk_EMsgGCPresets_SetItemPosition = 1064,
  EGCItemMsgk_EMsgGC_ReportAbuse = 1065,
  EGCItemMsgk_EMsgGC_ReportAbuseResponse = 1066,
  EGCItemMsgk_EMsgGCPresets_SelectPresetForClassReply = 1067,
  EGCItemMsgk_EMsgGCNameItemNotification = 1068,
  EGCItemMsgk_EMsgGCApplyConsumableEffects = 1069,
  EGCItemMsgk_EMsgGCConsumableExhausted = 1070,
  EGCItemMsgk_EMsgGCShowItemsPickedUp = 1071,
  EGCItemMsgk_EMsgGCClientDisplayNotification = 1072,
  EGCItemMsgk_EMsgGCApplyStrangePart = 1073,
  EGCItemMsgk_EMsgGC_IncrementKillCountAttribute = 1074,
  EGCItemMsgk_EMsgGC_IncrementKillCountResponse = 1075,
  EGCItemMsgk_EMsgGCApplyPennantUpgrade = 1076,
  EGCItemMsgk_EMsgGCSetItemPositions = 1077,
  EGCItemMsgk_EMsgGCApplyEggEssence = 1078,
  EGCItemMsgk_EMsgGCNameEggEssenceResponse = 1079,
  EGCItemMsgk_EMsgGCTradingBase = 1500,
  EGCItemMsgk_EMsgGCTrading_InitiateTradeRequest = 1501,
  EGCItemMsgk_EMsgGCTrading_InitiateTradeResponse = 1502,
  EGCItemMsgk_EMsgGCTrading_StartSession = 1503,
  EGCItemMsgk_EMsgGCTrading_SetItem = 1504,
  EGCItemMsgk_EMsgGCTrading_RemoveItem = 1505,
  EGCItemMsgk_EMsgGCTrading_UpdateTradeInfo = 1506,
  EGCItemMsgk_EMsgGCTrading_SetReadiness = 1507,
  EGCItemMsgk_EMsgGCTrading_ReadinessResponse = 1508,
  EGCItemMsgk_EMsgGCTrading_SessionClosed = 1509,
  EGCItemMsgk_EMsgGCTrading_CancelSession = 1510,
  EGCItemMsgk_EMsgGCTrading_TradeChatMsg = 1511,
  EGCItemMsgk_EMsgGCTrading_ConfirmOffer = 1512,
  EGCItemMsgk_EMsgGCTrading_TradeTypingChatMsg = 1513,
  EGCItemMsgk_EMsgGCServerBrowser_FavoriteServer = 1601,
  EGCItemMsgk_EMsgGCServerBrowser_BlacklistServer = 1602,
  EGCItemMsgk_EMsgGCServerRentalsBase = 1700,
  EGCItemMsgk_EMsgGCItemPreviewCheckStatus = 1701,
  EGCItemMsgk_EMsgGCItemPreviewStatusResponse = 1702,
  EGCItemMsgk_EMsgGCItemPreviewRequest = 1703,
  EGCItemMsgk_EMsgGCItemPreviewRequestResponse = 1704,
  EGCItemMsgk_EMsgGCItemPreviewExpire = 1705,
  EGCItemMsgk_EMsgGCItemPreviewExpireNotification = 1706,
  EGCItemMsgk_EMsgGCItemPreviewItemBoughtNotification = 1707,
  EGCItemMsgk_EMsgGCDev_NewItemRequest = 2001,
  EGCItemMsgk_EMsgGCDev_NewItemRequestResponse = 2002,
  EGCItemMsgk_EMsgGCStoreGetUserData = 2500,
  EGCItemMsgk_EMsgGCStoreGetUserDataResponse = 2501,
  EGCItemMsgk_EMsgGCStorePurchaseInit_DEPRECATED = 2502,
  EGCItemMsgk_EMsgGCStorePurchaseInitResponse_DEPRECATED = 2503,
  EGCItemMsgk_EMsgGCStorePurchaseFinalize = 2504,
  EGCItemMsgk_EMsgGCStorePurchaseFinalizeResponse = 2505,
  EGCItemMsgk_EMsgGCStorePurchaseCancel = 2506,
  EGCItemMsgk_EMsgGCStorePurchaseCancelResponse = 2507,
  EGCItemMsgk_EMsgGCStorePurchaseQueryTxn = 2508,
  EGCItemMsgk_EMsgGCStorePurchaseQueryTxnResponse = 2509,
  EGCItemMsgk_EMsgGCStorePurchaseInit = 2510,
  EGCItemMsgk_EMsgGCStorePurchaseInitResponse = 2511,
  EGCItemMsgk_EMsgGCBannedWordListRequest = 2512,
  EGCItemMsgk_EMsgGCBannedWordListResponse = 2513,
  EGCItemMsgk_EMsgGCToGCBannedWordListBroadcast = 2514,
} EGCItemMsg;

BOOL EGCItemMsgIsValidValue(EGCItemMsg value);

typedef enum {
  EGCMsgResponsek_EGCMsgResponseOK = 0,
  EGCMsgResponsek_EGCMsgResponseDenied = 1,
  EGCMsgResponsek_EGCMsgResponseServerError = 2,
  EGCMsgResponsek_EGCMsgResponseTimeout = 3,
  EGCMsgResponsek_EGCMsgResponseInvalid = 4,
  EGCMsgResponsek_EGCMsgResponseNoMatch = 5,
  EGCMsgResponsek_EGCMsgResponseUnknownError = 6,
  EGCMsgResponsek_EGCMsgResponseNotLoggedOn = 7,
  EGCMsgResponsek_EGCMsgFailedToCreate = 8,
} EGCMsgResponse;

BOOL EGCMsgResponseIsValidValue(EGCMsgResponse value);


@interface EconGcmessagesRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

