// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "econ_gcmessages.pb.h"

@implementation EconGcmessagesRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EconGcmessagesRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [SteammessagesRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL EGCItemMsgIsValidValue(EGCItemMsg value) {
  switch (value) {
    case EGCItemMsgk_EMsgGCBase:
    case EGCItemMsgk_EMsgGCSetItemPosition:
    case EGCItemMsgk_EMsgGCCraft:
    case EGCItemMsgk_EMsgGCCraftResponse:
    case EGCItemMsgk_EMsgGCDelete:
    case EGCItemMsgk_EMsgGCVerifyCacheSubscription:
    case EGCItemMsgk_EMsgGCNameItem:
    case EGCItemMsgk_EMsgGCUnlockCrate:
    case EGCItemMsgk_EMsgGCUnlockCrateResponse:
    case EGCItemMsgk_EMsgGCPaintItem:
    case EGCItemMsgk_EMsgGCPaintItemResponse:
    case EGCItemMsgk_EMsgGCGoldenWrenchBroadcast:
    case EGCItemMsgk_EMsgGCMOTDRequest:
    case EGCItemMsgk_EMsgGCMOTDRequestResponse:
    case EGCItemMsgk_EMsgGCAddItemToSocket_DEPRECATED:
    case EGCItemMsgk_EMsgGCAddItemToSocketResponse_DEPRECATED:
    case EGCItemMsgk_EMsgGCAddSocketToBaseItem_DEPRECATED:
    case EGCItemMsgk_EMsgGCAddSocketToItem_DEPRECATED:
    case EGCItemMsgk_EMsgGCAddSocketToItemResponse_DEPRECATED:
    case EGCItemMsgk_EMsgGCNameBaseItem:
    case EGCItemMsgk_EMsgGCNameBaseItemResponse:
    case EGCItemMsgk_EMsgGCRemoveSocketItem_DEPRECATED:
    case EGCItemMsgk_EMsgGCRemoveSocketItemResponse_DEPRECATED:
    case EGCItemMsgk_EMsgGCCustomizeItemTexture:
    case EGCItemMsgk_EMsgGCCustomizeItemTextureResponse:
    case EGCItemMsgk_EMsgGCUseItemRequest:
    case EGCItemMsgk_EMsgGCUseItemResponse:
    case EGCItemMsgk_EMsgGCGiftedItems:
    case EGCItemMsgk_EMsgGCSpawnItem_DEPRECATED:
    case EGCItemMsgk_EMsgGCRespawnPostLoadoutChange:
    case EGCItemMsgk_EMsgGCRemoveItemName:
    case EGCItemMsgk_EMsgGCRemoveItemPaint:
    case EGCItemMsgk_EMsgGCGiftWrapItem:
    case EGCItemMsgk_EMsgGCGiftWrapItemResponse:
    case EGCItemMsgk_EMsgGCDeliverGift:
    case EGCItemMsgk_EMsgGCDeliverGiftResponseGiver:
    case EGCItemMsgk_EMsgGCDeliverGiftResponseReceiver:
    case EGCItemMsgk_EMsgGCUnwrapGiftRequest:
    case EGCItemMsgk_EMsgGCUnwrapGiftResponse:
    case EGCItemMsgk_EMsgGCSetItemStyle:
    case EGCItemMsgk_EMsgGCUsedClaimCodeItem:
    case EGCItemMsgk_EMsgGCSortItems:
    case EGCItemMsgk_EMsgGC_RevolvingLootList_DEPRECATED:
    case EGCItemMsgk_EMsgGCLookupAccount:
    case EGCItemMsgk_EMsgGCLookupAccountResponse:
    case EGCItemMsgk_EMsgGCLookupAccountName:
    case EGCItemMsgk_EMsgGCLookupAccountNameResponse:
    case EGCItemMsgk_EMsgGCUpdateItemSchema:
    case EGCItemMsgk_EMsgGCRequestInventoryRefresh:
    case EGCItemMsgk_EMsgGCRemoveCustomTexture:
    case EGCItemMsgk_EMsgGCRemoveCustomTextureResponse:
    case EGCItemMsgk_EMsgGCRemoveMakersMark:
    case EGCItemMsgk_EMsgGCRemoveMakersMarkResponse:
    case EGCItemMsgk_EMsgGCRemoveUniqueCraftIndex:
    case EGCItemMsgk_EMsgGCRemoveUniqueCraftIndexResponse:
    case EGCItemMsgk_EMsgGCSaxxyBroadcast:
    case EGCItemMsgk_EMsgGCBackpackSortFinished:
    case EGCItemMsgk_EMsgGCAdjustItemEquippedState:
    case EGCItemMsgk_EMsgGCCollectItem:
    case EGCItemMsgk_EMsgGCItemAcknowledged:
    case EGCItemMsgk_EMsgGCPresets_SelectPresetForClass:
    case EGCItemMsgk_EMsgGCPresets_SetItemPosition:
    case EGCItemMsgk_EMsgGC_ReportAbuse:
    case EGCItemMsgk_EMsgGC_ReportAbuseResponse:
    case EGCItemMsgk_EMsgGCPresets_SelectPresetForClassReply:
    case EGCItemMsgk_EMsgGCNameItemNotification:
    case EGCItemMsgk_EMsgGCApplyConsumableEffects:
    case EGCItemMsgk_EMsgGCConsumableExhausted:
    case EGCItemMsgk_EMsgGCShowItemsPickedUp:
    case EGCItemMsgk_EMsgGCClientDisplayNotification:
    case EGCItemMsgk_EMsgGCApplyStrangePart:
    case EGCItemMsgk_EMsgGC_IncrementKillCountAttribute:
    case EGCItemMsgk_EMsgGC_IncrementKillCountResponse:
    case EGCItemMsgk_EMsgGCApplyPennantUpgrade:
    case EGCItemMsgk_EMsgGCSetItemPositions:
    case EGCItemMsgk_EMsgGCApplyEggEssence:
    case EGCItemMsgk_EMsgGCNameEggEssenceResponse:
    case EGCItemMsgk_EMsgGCTradingBase:
    case EGCItemMsgk_EMsgGCTrading_InitiateTradeRequest:
    case EGCItemMsgk_EMsgGCTrading_InitiateTradeResponse:
    case EGCItemMsgk_EMsgGCTrading_StartSession:
    case EGCItemMsgk_EMsgGCTrading_SetItem:
    case EGCItemMsgk_EMsgGCTrading_RemoveItem:
    case EGCItemMsgk_EMsgGCTrading_UpdateTradeInfo:
    case EGCItemMsgk_EMsgGCTrading_SetReadiness:
    case EGCItemMsgk_EMsgGCTrading_ReadinessResponse:
    case EGCItemMsgk_EMsgGCTrading_SessionClosed:
    case EGCItemMsgk_EMsgGCTrading_CancelSession:
    case EGCItemMsgk_EMsgGCTrading_TradeChatMsg:
    case EGCItemMsgk_EMsgGCTrading_ConfirmOffer:
    case EGCItemMsgk_EMsgGCTrading_TradeTypingChatMsg:
    case EGCItemMsgk_EMsgGCServerBrowser_FavoriteServer:
    case EGCItemMsgk_EMsgGCServerBrowser_BlacklistServer:
    case EGCItemMsgk_EMsgGCServerRentalsBase:
    case EGCItemMsgk_EMsgGCItemPreviewCheckStatus:
    case EGCItemMsgk_EMsgGCItemPreviewStatusResponse:
    case EGCItemMsgk_EMsgGCItemPreviewRequest:
    case EGCItemMsgk_EMsgGCItemPreviewRequestResponse:
    case EGCItemMsgk_EMsgGCItemPreviewExpire:
    case EGCItemMsgk_EMsgGCItemPreviewExpireNotification:
    case EGCItemMsgk_EMsgGCItemPreviewItemBoughtNotification:
    case EGCItemMsgk_EMsgGCDev_NewItemRequest:
    case EGCItemMsgk_EMsgGCDev_NewItemRequestResponse:
    case EGCItemMsgk_EMsgGCStoreGetUserData:
    case EGCItemMsgk_EMsgGCStoreGetUserDataResponse:
    case EGCItemMsgk_EMsgGCStorePurchaseInit_DEPRECATED:
    case EGCItemMsgk_EMsgGCStorePurchaseInitResponse_DEPRECATED:
    case EGCItemMsgk_EMsgGCStorePurchaseFinalize:
    case EGCItemMsgk_EMsgGCStorePurchaseFinalizeResponse:
    case EGCItemMsgk_EMsgGCStorePurchaseCancel:
    case EGCItemMsgk_EMsgGCStorePurchaseCancelResponse:
    case EGCItemMsgk_EMsgGCStorePurchaseQueryTxn:
    case EGCItemMsgk_EMsgGCStorePurchaseQueryTxnResponse:
    case EGCItemMsgk_EMsgGCStorePurchaseInit:
    case EGCItemMsgk_EMsgGCStorePurchaseInitResponse:
    case EGCItemMsgk_EMsgGCBannedWordListRequest:
    case EGCItemMsgk_EMsgGCBannedWordListResponse:
    case EGCItemMsgk_EMsgGCToGCBannedWordListBroadcast:
      return YES;
    default:
      return NO;
  }
}
BOOL EGCMsgResponseIsValidValue(EGCMsgResponse value) {
  switch (value) {
    case EGCMsgResponsek_EGCMsgResponseOK:
    case EGCMsgResponsek_EGCMsgResponseDenied:
    case EGCMsgResponsek_EGCMsgResponseServerError:
    case EGCMsgResponsek_EGCMsgResponseTimeout:
    case EGCMsgResponsek_EGCMsgResponseInvalid:
    case EGCMsgResponsek_EGCMsgResponseNoMatch:
    case EGCMsgResponsek_EGCMsgResponseUnknownError:
    case EGCMsgResponsek_EGCMsgResponseNotLoggedOn:
    case EGCMsgResponsek_EGCMsgFailedToCreate:
      return YES;
    default:
      return NO;
  }
}
