// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class CMsgAccountDetails;
@class CMsgAccountDetails_Builder;
@class CMsgGCMultiplexMessage;
@class CMsgGCMultiplexMessage_Builder;
@class CMsgSOCacheSubscribed;
@class CMsgSOCacheSubscribed_Builder;
@class CMsgSOCacheSubscribed_SubscribedType;
@class CMsgSOCacheSubscribed_SubscribedType_Builder;
@class CMsgSOCacheSubscriptionCheck;
@class CMsgSOCacheSubscriptionCheck_Builder;
@class CMsgSOCacheSubscriptionRefresh;
@class CMsgSOCacheSubscriptionRefresh_Builder;
@class CMsgSOCacheUnsubscribed;
@class CMsgSOCacheUnsubscribed_Builder;
@class CMsgSOCacheVersion;
@class CMsgSOCacheVersion_Builder;
@class CMsgSOMultipleObjects;
@class CMsgSOMultipleObjects_Builder;
@class CMsgSOMultipleObjects_SingleObject;
@class CMsgSOMultipleObjects_SingleObject_Builder;
@class CMsgSOSingleObject;
@class CMsgSOSingleObject_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GcsdkGcmessagesRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CMsgSOSingleObject : PBGeneratedMessage {
@private
  BOOL hasTypeId_:1;
  BOOL hasOwner_:1;
  BOOL hasVersion_:1;
  BOOL hasObjectData_:1;
  int32_t typeId;
  uint64_t owner;
  uint64_t version;
  NSData* objectData;
}
- (BOOL) hasOwner;
- (BOOL) hasTypeId;
- (BOOL) hasObjectData;
- (BOOL) hasVersion;
@property (readonly) uint64_t owner;
@property (readonly) int32_t typeId;
@property (readonly, retain) NSData* objectData;
@property (readonly) uint64_t version;

+ (CMsgSOSingleObject*) defaultInstance;
- (CMsgSOSingleObject*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOSingleObject_Builder*) builder;
+ (CMsgSOSingleObject_Builder*) builder;
+ (CMsgSOSingleObject_Builder*) builderWithPrototype:(CMsgSOSingleObject*) prototype;
- (CMsgSOSingleObject_Builder*) toBuilder;

+ (CMsgSOSingleObject*) parseFromData:(NSData*) data;
+ (CMsgSOSingleObject*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOSingleObject*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOSingleObject*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOSingleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOSingleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOSingleObject_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOSingleObject* result;
}

- (CMsgSOSingleObject*) defaultInstance;

- (CMsgSOSingleObject_Builder*) clear;
- (CMsgSOSingleObject_Builder*) clone;

- (CMsgSOSingleObject*) build;
- (CMsgSOSingleObject*) buildPartial;

- (CMsgSOSingleObject_Builder*) mergeFrom:(CMsgSOSingleObject*) other;
- (CMsgSOSingleObject_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOSingleObject_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOSingleObject_Builder*) setOwner:(uint64_t) value;
- (CMsgSOSingleObject_Builder*) clearOwner;

- (BOOL) hasTypeId;
- (int32_t) typeId;
- (CMsgSOSingleObject_Builder*) setTypeId:(int32_t) value;
- (CMsgSOSingleObject_Builder*) clearTypeId;

- (BOOL) hasObjectData;
- (NSData*) objectData;
- (CMsgSOSingleObject_Builder*) setObjectData:(NSData*) value;
- (CMsgSOSingleObject_Builder*) clearObjectData;

- (BOOL) hasVersion;
- (uint64_t) version;
- (CMsgSOSingleObject_Builder*) setVersion:(uint64_t) value;
- (CMsgSOSingleObject_Builder*) clearVersion;
@end

@interface CMsgSOMultipleObjects : PBGeneratedMessage {
@private
  BOOL hasOwner_:1;
  BOOL hasVersion_:1;
  uint64_t owner;
  uint64_t version;
  PBAppendableArray * objectsModifiedArray;
  PBAppendableArray * objectsAddedArray;
  PBAppendableArray * objectsRemovedArray;
}
- (BOOL) hasOwner;
- (BOOL) hasVersion;
@property (readonly) uint64_t owner;
@property (readonly, retain) PBArray * objectsModified;
@property (readonly) uint64_t version;
@property (readonly, retain) PBArray * objectsAdded;
@property (readonly, retain) PBArray * objectsRemoved;
- (CMsgSOMultipleObjects_SingleObject*)objectsModifiedAtIndex:(NSUInteger)index;
- (CMsgSOMultipleObjects_SingleObject*)objectsAddedAtIndex:(NSUInteger)index;
- (CMsgSOMultipleObjects_SingleObject*)objectsRemovedAtIndex:(NSUInteger)index;

+ (CMsgSOMultipleObjects*) defaultInstance;
- (CMsgSOMultipleObjects*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOMultipleObjects_Builder*) builder;
+ (CMsgSOMultipleObjects_Builder*) builder;
+ (CMsgSOMultipleObjects_Builder*) builderWithPrototype:(CMsgSOMultipleObjects*) prototype;
- (CMsgSOMultipleObjects_Builder*) toBuilder;

+ (CMsgSOMultipleObjects*) parseFromData:(NSData*) data;
+ (CMsgSOMultipleObjects*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOMultipleObjects*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOMultipleObjects*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOMultipleObjects*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOMultipleObjects*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOMultipleObjects_SingleObject : PBGeneratedMessage {
@private
  BOOL hasTypeId_:1;
  BOOL hasObjectData_:1;
  int32_t typeId;
  NSData* objectData;
}
- (BOOL) hasTypeId;
- (BOOL) hasObjectData;
@property (readonly) int32_t typeId;
@property (readonly, retain) NSData* objectData;

+ (CMsgSOMultipleObjects_SingleObject*) defaultInstance;
- (CMsgSOMultipleObjects_SingleObject*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOMultipleObjects_SingleObject_Builder*) builder;
+ (CMsgSOMultipleObjects_SingleObject_Builder*) builder;
+ (CMsgSOMultipleObjects_SingleObject_Builder*) builderWithPrototype:(CMsgSOMultipleObjects_SingleObject*) prototype;
- (CMsgSOMultipleObjects_SingleObject_Builder*) toBuilder;

+ (CMsgSOMultipleObjects_SingleObject*) parseFromData:(NSData*) data;
+ (CMsgSOMultipleObjects_SingleObject*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOMultipleObjects_SingleObject*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOMultipleObjects_SingleObject*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOMultipleObjects_SingleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOMultipleObjects_SingleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOMultipleObjects_SingleObject_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOMultipleObjects_SingleObject* result;
}

- (CMsgSOMultipleObjects_SingleObject*) defaultInstance;

- (CMsgSOMultipleObjects_SingleObject_Builder*) clear;
- (CMsgSOMultipleObjects_SingleObject_Builder*) clone;

- (CMsgSOMultipleObjects_SingleObject*) build;
- (CMsgSOMultipleObjects_SingleObject*) buildPartial;

- (CMsgSOMultipleObjects_SingleObject_Builder*) mergeFrom:(CMsgSOMultipleObjects_SingleObject*) other;
- (CMsgSOMultipleObjects_SingleObject_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOMultipleObjects_SingleObject_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTypeId;
- (int32_t) typeId;
- (CMsgSOMultipleObjects_SingleObject_Builder*) setTypeId:(int32_t) value;
- (CMsgSOMultipleObjects_SingleObject_Builder*) clearTypeId;

- (BOOL) hasObjectData;
- (NSData*) objectData;
- (CMsgSOMultipleObjects_SingleObject_Builder*) setObjectData:(NSData*) value;
- (CMsgSOMultipleObjects_SingleObject_Builder*) clearObjectData;
@end

@interface CMsgSOMultipleObjects_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOMultipleObjects* result;
}

- (CMsgSOMultipleObjects*) defaultInstance;

- (CMsgSOMultipleObjects_Builder*) clear;
- (CMsgSOMultipleObjects_Builder*) clone;

- (CMsgSOMultipleObjects*) build;
- (CMsgSOMultipleObjects*) buildPartial;

- (CMsgSOMultipleObjects_Builder*) mergeFrom:(CMsgSOMultipleObjects*) other;
- (CMsgSOMultipleObjects_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOMultipleObjects_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOMultipleObjects_Builder*) setOwner:(uint64_t) value;
- (CMsgSOMultipleObjects_Builder*) clearOwner;

- (PBAppendableArray *)objectsModified;
- (CMsgSOMultipleObjects_SingleObject*)objectsModifiedAtIndex:(NSUInteger)index;
- (CMsgSOMultipleObjects_Builder *)addObjectsModified:(CMsgSOMultipleObjects_SingleObject*)value;
- (CMsgSOMultipleObjects_Builder *)setObjectsModifiedArray:(NSArray *)array;
- (CMsgSOMultipleObjects_Builder *)setObjectsModifiedValues:(const CMsgSOMultipleObjects_SingleObject* *)values count:(NSUInteger)count;
- (CMsgSOMultipleObjects_Builder *)clearObjectsModified;

- (BOOL) hasVersion;
- (uint64_t) version;
- (CMsgSOMultipleObjects_Builder*) setVersion:(uint64_t) value;
- (CMsgSOMultipleObjects_Builder*) clearVersion;

- (PBAppendableArray *)objectsAdded;
- (CMsgSOMultipleObjects_SingleObject*)objectsAddedAtIndex:(NSUInteger)index;
- (CMsgSOMultipleObjects_Builder *)addObjectsAdded:(CMsgSOMultipleObjects_SingleObject*)value;
- (CMsgSOMultipleObjects_Builder *)setObjectsAddedArray:(NSArray *)array;
- (CMsgSOMultipleObjects_Builder *)setObjectsAddedValues:(const CMsgSOMultipleObjects_SingleObject* *)values count:(NSUInteger)count;
- (CMsgSOMultipleObjects_Builder *)clearObjectsAdded;

- (PBAppendableArray *)objectsRemoved;
- (CMsgSOMultipleObjects_SingleObject*)objectsRemovedAtIndex:(NSUInteger)index;
- (CMsgSOMultipleObjects_Builder *)addObjectsRemoved:(CMsgSOMultipleObjects_SingleObject*)value;
- (CMsgSOMultipleObjects_Builder *)setObjectsRemovedArray:(NSArray *)array;
- (CMsgSOMultipleObjects_Builder *)setObjectsRemovedValues:(const CMsgSOMultipleObjects_SingleObject* *)values count:(NSUInteger)count;
- (CMsgSOMultipleObjects_Builder *)clearObjectsRemoved;
@end

@interface CMsgSOCacheSubscribed : PBGeneratedMessage {
@private
  BOOL hasOwner_:1;
  BOOL hasVersion_:1;
  uint64_t owner;
  uint64_t version;
  PBAppendableArray * objectsArray;
}
- (BOOL) hasOwner;
- (BOOL) hasVersion;
@property (readonly) uint64_t owner;
@property (readonly, retain) PBArray * objects;
@property (readonly) uint64_t version;
- (CMsgSOCacheSubscribed_SubscribedType*)objectsAtIndex:(NSUInteger)index;

+ (CMsgSOCacheSubscribed*) defaultInstance;
- (CMsgSOCacheSubscribed*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheSubscribed_Builder*) builder;
+ (CMsgSOCacheSubscribed_Builder*) builder;
+ (CMsgSOCacheSubscribed_Builder*) builderWithPrototype:(CMsgSOCacheSubscribed*) prototype;
- (CMsgSOCacheSubscribed_Builder*) toBuilder;

+ (CMsgSOCacheSubscribed*) parseFromData:(NSData*) data;
+ (CMsgSOCacheSubscribed*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscribed*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheSubscribed*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscribed*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheSubscribed*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheSubscribed_SubscribedType : PBGeneratedMessage {
@private
  BOOL hasTypeId_:1;
  int32_t typeId;
  PBAppendableArray * objectDataArray;
}
- (BOOL) hasTypeId;
@property (readonly) int32_t typeId;
@property (readonly, retain) PBArray * objectData;
- (NSData*)objectDataAtIndex:(NSUInteger)index;

+ (CMsgSOCacheSubscribed_SubscribedType*) defaultInstance;
- (CMsgSOCacheSubscribed_SubscribedType*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) builder;
+ (CMsgSOCacheSubscribed_SubscribedType_Builder*) builder;
+ (CMsgSOCacheSubscribed_SubscribedType_Builder*) builderWithPrototype:(CMsgSOCacheSubscribed_SubscribedType*) prototype;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) toBuilder;

+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromData:(NSData*) data;
+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheSubscribed_SubscribedType*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheSubscribed_SubscribedType_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheSubscribed_SubscribedType* result;
}

- (CMsgSOCacheSubscribed_SubscribedType*) defaultInstance;

- (CMsgSOCacheSubscribed_SubscribedType_Builder*) clear;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) clone;

- (CMsgSOCacheSubscribed_SubscribedType*) build;
- (CMsgSOCacheSubscribed_SubscribedType*) buildPartial;

- (CMsgSOCacheSubscribed_SubscribedType_Builder*) mergeFrom:(CMsgSOCacheSubscribed_SubscribedType*) other;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTypeId;
- (int32_t) typeId;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) setTypeId:(int32_t) value;
- (CMsgSOCacheSubscribed_SubscribedType_Builder*) clearTypeId;

- (PBAppendableArray *)objectData;
- (NSData*)objectDataAtIndex:(NSUInteger)index;
- (CMsgSOCacheSubscribed_SubscribedType_Builder *)addObjectData:(NSData*)value;
- (CMsgSOCacheSubscribed_SubscribedType_Builder *)setObjectDataArray:(NSArray *)array;
- (CMsgSOCacheSubscribed_SubscribedType_Builder *)setObjectDataValues:(const NSData* *)values count:(NSUInteger)count;
- (CMsgSOCacheSubscribed_SubscribedType_Builder *)clearObjectData;
@end

@interface CMsgSOCacheSubscribed_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheSubscribed* result;
}

- (CMsgSOCacheSubscribed*) defaultInstance;

- (CMsgSOCacheSubscribed_Builder*) clear;
- (CMsgSOCacheSubscribed_Builder*) clone;

- (CMsgSOCacheSubscribed*) build;
- (CMsgSOCacheSubscribed*) buildPartial;

- (CMsgSOCacheSubscribed_Builder*) mergeFrom:(CMsgSOCacheSubscribed*) other;
- (CMsgSOCacheSubscribed_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheSubscribed_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOCacheSubscribed_Builder*) setOwner:(uint64_t) value;
- (CMsgSOCacheSubscribed_Builder*) clearOwner;

- (PBAppendableArray *)objects;
- (CMsgSOCacheSubscribed_SubscribedType*)objectsAtIndex:(NSUInteger)index;
- (CMsgSOCacheSubscribed_Builder *)addObjects:(CMsgSOCacheSubscribed_SubscribedType*)value;
- (CMsgSOCacheSubscribed_Builder *)setObjectsArray:(NSArray *)array;
- (CMsgSOCacheSubscribed_Builder *)setObjectsValues:(const CMsgSOCacheSubscribed_SubscribedType* *)values count:(NSUInteger)count;
- (CMsgSOCacheSubscribed_Builder *)clearObjects;

- (BOOL) hasVersion;
- (uint64_t) version;
- (CMsgSOCacheSubscribed_Builder*) setVersion:(uint64_t) value;
- (CMsgSOCacheSubscribed_Builder*) clearVersion;
@end

@interface CMsgSOCacheUnsubscribed : PBGeneratedMessage {
@private
  BOOL hasOwner_:1;
  uint64_t owner;
}
- (BOOL) hasOwner;
@property (readonly) uint64_t owner;

+ (CMsgSOCacheUnsubscribed*) defaultInstance;
- (CMsgSOCacheUnsubscribed*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheUnsubscribed_Builder*) builder;
+ (CMsgSOCacheUnsubscribed_Builder*) builder;
+ (CMsgSOCacheUnsubscribed_Builder*) builderWithPrototype:(CMsgSOCacheUnsubscribed*) prototype;
- (CMsgSOCacheUnsubscribed_Builder*) toBuilder;

+ (CMsgSOCacheUnsubscribed*) parseFromData:(NSData*) data;
+ (CMsgSOCacheUnsubscribed*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheUnsubscribed*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheUnsubscribed*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheUnsubscribed*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheUnsubscribed*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheUnsubscribed_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheUnsubscribed* result;
}

- (CMsgSOCacheUnsubscribed*) defaultInstance;

- (CMsgSOCacheUnsubscribed_Builder*) clear;
- (CMsgSOCacheUnsubscribed_Builder*) clone;

- (CMsgSOCacheUnsubscribed*) build;
- (CMsgSOCacheUnsubscribed*) buildPartial;

- (CMsgSOCacheUnsubscribed_Builder*) mergeFrom:(CMsgSOCacheUnsubscribed*) other;
- (CMsgSOCacheUnsubscribed_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheUnsubscribed_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOCacheUnsubscribed_Builder*) setOwner:(uint64_t) value;
- (CMsgSOCacheUnsubscribed_Builder*) clearOwner;
@end

@interface CMsgSOCacheSubscriptionCheck : PBGeneratedMessage {
@private
  BOOL hasOwner_:1;
  BOOL hasVersion_:1;
  uint64_t owner;
  uint64_t version;
}
- (BOOL) hasOwner;
- (BOOL) hasVersion;
@property (readonly) uint64_t owner;
@property (readonly) uint64_t version;

+ (CMsgSOCacheSubscriptionCheck*) defaultInstance;
- (CMsgSOCacheSubscriptionCheck*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheSubscriptionCheck_Builder*) builder;
+ (CMsgSOCacheSubscriptionCheck_Builder*) builder;
+ (CMsgSOCacheSubscriptionCheck_Builder*) builderWithPrototype:(CMsgSOCacheSubscriptionCheck*) prototype;
- (CMsgSOCacheSubscriptionCheck_Builder*) toBuilder;

+ (CMsgSOCacheSubscriptionCheck*) parseFromData:(NSData*) data;
+ (CMsgSOCacheSubscriptionCheck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscriptionCheck*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheSubscriptionCheck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscriptionCheck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheSubscriptionCheck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheSubscriptionCheck_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheSubscriptionCheck* result;
}

- (CMsgSOCacheSubscriptionCheck*) defaultInstance;

- (CMsgSOCacheSubscriptionCheck_Builder*) clear;
- (CMsgSOCacheSubscriptionCheck_Builder*) clone;

- (CMsgSOCacheSubscriptionCheck*) build;
- (CMsgSOCacheSubscriptionCheck*) buildPartial;

- (CMsgSOCacheSubscriptionCheck_Builder*) mergeFrom:(CMsgSOCacheSubscriptionCheck*) other;
- (CMsgSOCacheSubscriptionCheck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheSubscriptionCheck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOCacheSubscriptionCheck_Builder*) setOwner:(uint64_t) value;
- (CMsgSOCacheSubscriptionCheck_Builder*) clearOwner;

- (BOOL) hasVersion;
- (uint64_t) version;
- (CMsgSOCacheSubscriptionCheck_Builder*) setVersion:(uint64_t) value;
- (CMsgSOCacheSubscriptionCheck_Builder*) clearVersion;
@end

@interface CMsgSOCacheSubscriptionRefresh : PBGeneratedMessage {
@private
  BOOL hasOwner_:1;
  uint64_t owner;
}
- (BOOL) hasOwner;
@property (readonly) uint64_t owner;

+ (CMsgSOCacheSubscriptionRefresh*) defaultInstance;
- (CMsgSOCacheSubscriptionRefresh*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheSubscriptionRefresh_Builder*) builder;
+ (CMsgSOCacheSubscriptionRefresh_Builder*) builder;
+ (CMsgSOCacheSubscriptionRefresh_Builder*) builderWithPrototype:(CMsgSOCacheSubscriptionRefresh*) prototype;
- (CMsgSOCacheSubscriptionRefresh_Builder*) toBuilder;

+ (CMsgSOCacheSubscriptionRefresh*) parseFromData:(NSData*) data;
+ (CMsgSOCacheSubscriptionRefresh*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscriptionRefresh*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheSubscriptionRefresh*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheSubscriptionRefresh*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheSubscriptionRefresh*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheSubscriptionRefresh_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheSubscriptionRefresh* result;
}

- (CMsgSOCacheSubscriptionRefresh*) defaultInstance;

- (CMsgSOCacheSubscriptionRefresh_Builder*) clear;
- (CMsgSOCacheSubscriptionRefresh_Builder*) clone;

- (CMsgSOCacheSubscriptionRefresh*) build;
- (CMsgSOCacheSubscriptionRefresh*) buildPartial;

- (CMsgSOCacheSubscriptionRefresh_Builder*) mergeFrom:(CMsgSOCacheSubscriptionRefresh*) other;
- (CMsgSOCacheSubscriptionRefresh_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheSubscriptionRefresh_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwner;
- (uint64_t) owner;
- (CMsgSOCacheSubscriptionRefresh_Builder*) setOwner:(uint64_t) value;
- (CMsgSOCacheSubscriptionRefresh_Builder*) clearOwner;
@end

@interface CMsgSOCacheVersion : PBGeneratedMessage {
@private
  BOOL hasVersion_:1;
  uint64_t version;
}
- (BOOL) hasVersion;
@property (readonly) uint64_t version;

+ (CMsgSOCacheVersion*) defaultInstance;
- (CMsgSOCacheVersion*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSOCacheVersion_Builder*) builder;
+ (CMsgSOCacheVersion_Builder*) builder;
+ (CMsgSOCacheVersion_Builder*) builderWithPrototype:(CMsgSOCacheVersion*) prototype;
- (CMsgSOCacheVersion_Builder*) toBuilder;

+ (CMsgSOCacheVersion*) parseFromData:(NSData*) data;
+ (CMsgSOCacheVersion*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheVersion*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSOCacheVersion*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSOCacheVersion*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSOCacheVersion*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSOCacheVersion_Builder : PBGeneratedMessage_Builder {
@private
  CMsgSOCacheVersion* result;
}

- (CMsgSOCacheVersion*) defaultInstance;

- (CMsgSOCacheVersion_Builder*) clear;
- (CMsgSOCacheVersion_Builder*) clone;

- (CMsgSOCacheVersion*) build;
- (CMsgSOCacheVersion*) buildPartial;

- (CMsgSOCacheVersion_Builder*) mergeFrom:(CMsgSOCacheVersion*) other;
- (CMsgSOCacheVersion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSOCacheVersion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (uint64_t) version;
- (CMsgSOCacheVersion_Builder*) setVersion:(uint64_t) value;
- (CMsgSOCacheVersion_Builder*) clearVersion;
@end

@interface CMsgAccountDetails : PBGeneratedMessage {
@private
  BOOL hasValid_:1;
  BOOL hasPublicProfile_:1;
  BOOL hasPublicInventory_:1;
  BOOL hasVacBanned_:1;
  BOOL hasCyberCafe_:1;
  BOOL hasSchoolAccount_:1;
  BOOL hasFreeTrialAccount_:1;
  BOOL hasSubscribed_:1;
  BOOL hasLowViolence_:1;
  BOOL hasLimited_:1;
  BOOL hasTrusted_:1;
  BOOL hasTimeCached_:1;
  BOOL hasAccountName_:1;
  BOOL hasPackage_:1;
  BOOL valid_:1;
  BOOL publicProfile_:1;
  BOOL publicInventory_:1;
  BOOL vacBanned_:1;
  BOOL cyberCafe_:1;
  BOOL schoolAccount_:1;
  BOOL freeTrialAccount_:1;
  BOOL subscribed_:1;
  BOOL lowViolence_:1;
  BOOL limited_:1;
  BOOL trusted_:1;
  uint32_t timeCached;
  NSString* accountName;
  uint32_t package;
}
- (BOOL) hasValid;
- (BOOL) hasAccountName;
- (BOOL) hasPublicProfile;
- (BOOL) hasPublicInventory;
- (BOOL) hasVacBanned;
- (BOOL) hasCyberCafe;
- (BOOL) hasSchoolAccount;
- (BOOL) hasFreeTrialAccount;
- (BOOL) hasSubscribed;
- (BOOL) hasLowViolence;
- (BOOL) hasLimited;
- (BOOL) hasTrusted;
- (BOOL) hasPackage;
- (BOOL) hasTimeCached;
- (BOOL) valid;
@property (readonly, retain) NSString* accountName;
- (BOOL) publicProfile;
- (BOOL) publicInventory;
- (BOOL) vacBanned;
- (BOOL) cyberCafe;
- (BOOL) schoolAccount;
- (BOOL) freeTrialAccount;
- (BOOL) subscribed;
- (BOOL) lowViolence;
- (BOOL) limited;
- (BOOL) trusted;
@property (readonly) uint32_t package;
@property (readonly) uint32_t timeCached;

+ (CMsgAccountDetails*) defaultInstance;
- (CMsgAccountDetails*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgAccountDetails_Builder*) builder;
+ (CMsgAccountDetails_Builder*) builder;
+ (CMsgAccountDetails_Builder*) builderWithPrototype:(CMsgAccountDetails*) prototype;
- (CMsgAccountDetails_Builder*) toBuilder;

+ (CMsgAccountDetails*) parseFromData:(NSData*) data;
+ (CMsgAccountDetails*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAccountDetails*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgAccountDetails*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAccountDetails*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgAccountDetails*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgAccountDetails_Builder : PBGeneratedMessage_Builder {
@private
  CMsgAccountDetails* result;
}

- (CMsgAccountDetails*) defaultInstance;

- (CMsgAccountDetails_Builder*) clear;
- (CMsgAccountDetails_Builder*) clone;

- (CMsgAccountDetails*) build;
- (CMsgAccountDetails*) buildPartial;

- (CMsgAccountDetails_Builder*) mergeFrom:(CMsgAccountDetails*) other;
- (CMsgAccountDetails_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgAccountDetails_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValid;
- (BOOL) valid;
- (CMsgAccountDetails_Builder*) setValid:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearValid;

- (BOOL) hasAccountName;
- (NSString*) accountName;
- (CMsgAccountDetails_Builder*) setAccountName:(NSString*) value;
- (CMsgAccountDetails_Builder*) clearAccountName;

- (BOOL) hasPublicProfile;
- (BOOL) publicProfile;
- (CMsgAccountDetails_Builder*) setPublicProfile:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearPublicProfile;

- (BOOL) hasPublicInventory;
- (BOOL) publicInventory;
- (CMsgAccountDetails_Builder*) setPublicInventory:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearPublicInventory;

- (BOOL) hasVacBanned;
- (BOOL) vacBanned;
- (CMsgAccountDetails_Builder*) setVacBanned:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearVacBanned;

- (BOOL) hasCyberCafe;
- (BOOL) cyberCafe;
- (CMsgAccountDetails_Builder*) setCyberCafe:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearCyberCafe;

- (BOOL) hasSchoolAccount;
- (BOOL) schoolAccount;
- (CMsgAccountDetails_Builder*) setSchoolAccount:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearSchoolAccount;

- (BOOL) hasFreeTrialAccount;
- (BOOL) freeTrialAccount;
- (CMsgAccountDetails_Builder*) setFreeTrialAccount:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearFreeTrialAccount;

- (BOOL) hasSubscribed;
- (BOOL) subscribed;
- (CMsgAccountDetails_Builder*) setSubscribed:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearSubscribed;

- (BOOL) hasLowViolence;
- (BOOL) lowViolence;
- (CMsgAccountDetails_Builder*) setLowViolence:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearLowViolence;

- (BOOL) hasLimited;
- (BOOL) limited;
- (CMsgAccountDetails_Builder*) setLimited:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearLimited;

- (BOOL) hasTrusted;
- (BOOL) trusted;
- (CMsgAccountDetails_Builder*) setTrusted:(BOOL) value;
- (CMsgAccountDetails_Builder*) clearTrusted;

- (BOOL) hasPackage;
- (uint32_t) package;
- (CMsgAccountDetails_Builder*) setPackage:(uint32_t) value;
- (CMsgAccountDetails_Builder*) clearPackage;

- (BOOL) hasTimeCached;
- (uint32_t) timeCached;
- (CMsgAccountDetails_Builder*) setTimeCached:(uint32_t) value;
- (CMsgAccountDetails_Builder*) clearTimeCached;
@end

@interface CMsgGCMultiplexMessage : PBGeneratedMessage {
@private
  BOOL hasPayload_:1;
  BOOL hasMsgtype_:1;
  NSData* payload;
  uint32_t msgtype;
  PBAppendableArray * steamidsArray;
}
- (BOOL) hasMsgtype;
- (BOOL) hasPayload;
@property (readonly) uint32_t msgtype;
@property (readonly, retain) NSData* payload;
@property (readonly, retain) PBArray * steamids;
- (uint64_t)steamidsAtIndex:(NSUInteger)index;

+ (CMsgGCMultiplexMessage*) defaultInstance;
- (CMsgGCMultiplexMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGCMultiplexMessage_Builder*) builder;
+ (CMsgGCMultiplexMessage_Builder*) builder;
+ (CMsgGCMultiplexMessage_Builder*) builderWithPrototype:(CMsgGCMultiplexMessage*) prototype;
- (CMsgGCMultiplexMessage_Builder*) toBuilder;

+ (CMsgGCMultiplexMessage*) parseFromData:(NSData*) data;
+ (CMsgGCMultiplexMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGCMultiplexMessage*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGCMultiplexMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGCMultiplexMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGCMultiplexMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGCMultiplexMessage_Builder : PBGeneratedMessage_Builder {
@private
  CMsgGCMultiplexMessage* result;
}

- (CMsgGCMultiplexMessage*) defaultInstance;

- (CMsgGCMultiplexMessage_Builder*) clear;
- (CMsgGCMultiplexMessage_Builder*) clone;

- (CMsgGCMultiplexMessage*) build;
- (CMsgGCMultiplexMessage*) buildPartial;

- (CMsgGCMultiplexMessage_Builder*) mergeFrom:(CMsgGCMultiplexMessage*) other;
- (CMsgGCMultiplexMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGCMultiplexMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgtype;
- (uint32_t) msgtype;
- (CMsgGCMultiplexMessage_Builder*) setMsgtype:(uint32_t) value;
- (CMsgGCMultiplexMessage_Builder*) clearMsgtype;

- (BOOL) hasPayload;
- (NSData*) payload;
- (CMsgGCMultiplexMessage_Builder*) setPayload:(NSData*) value;
- (CMsgGCMultiplexMessage_Builder*) clearPayload;

- (PBAppendableArray *)steamids;
- (uint64_t)steamidsAtIndex:(NSUInteger)index;
- (CMsgGCMultiplexMessage_Builder *)addSteamids:(uint64_t)value;
- (CMsgGCMultiplexMessage_Builder *)setSteamidsArray:(NSArray *)array;
- (CMsgGCMultiplexMessage_Builder *)setSteamidsValues:(const uint64_t *)values count:(NSUInteger)count;
- (CMsgGCMultiplexMessage_Builder *)clearSteamids;
@end

