// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "matchmaker_common.pb.h"

@implementation MatchmakerCommonRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MatchmakerCommonRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL MatchTypeIsValidValue(MatchType value) {
  switch (value) {
    case MatchTypeMATCH_TYPE_RANKED:
    case MatchTypeMATCH_TYPE_COOP_BOTS:
    case MatchTypeMATCH_TYPE_TEAM_RANKED:
      return YES;
    default:
      return NO;
  }
}
BOOL DOTABotDifficultyIsValidValue(DOTABotDifficulty value) {
  switch (value) {
    case DOTABotDifficultyBOT_DIFFICULTY_PASSIVE:
    case DOTABotDifficultyBOT_DIFFICULTY_EASY:
    case DOTABotDifficultyBOT_DIFFICULTY_MEDIUM:
    case DOTABotDifficultyBOT_DIFFICULTY_HARD:
    case DOTABotDifficultyBOT_DIFFICULTY_UNFAIR:
    case DOTABotDifficultyBOT_DIFFICULTY_INVALID:
      return YES;
    default:
      return NO;
  }
}
