// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class ClientAppInfo;
@class ClientAppInfo_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface IclientObjectsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ClientAppInfo : PBGeneratedMessage {
@private
  BOOL hasFavorite_:1;
  BOOL hasInstalled_:1;
  BOOL hasAutoUpdate_:1;
  BOOL hasDownloading_:1;
  BOOL hasDownloadPaused_:1;
  BOOL hasChanging_:1;
  BOOL hasAvailableOnPlatform_:1;
  BOOL hasBytesDownloaded_:1;
  BOOL hasBytesNeeded_:1;
  BOOL hasCategory_:1;
  BOOL hasAppType_:1;
  BOOL hasAppid_:1;
  BOOL hasBytesDownloadRate_:1;
  BOOL favorite_:1;
  BOOL installed_:1;
  BOOL autoUpdate_:1;
  BOOL downloading_:1;
  BOOL downloadPaused_:1;
  BOOL changing_:1;
  BOOL availableOnPlatform_:1;
  uint64_t bytesDownloaded;
  uint64_t bytesNeeded;
  NSString* category;
  NSString* appType;
  uint32_t appid;
  uint32_t bytesDownloadRate;
}
- (BOOL) hasAppid;
- (BOOL) hasFavorite;
- (BOOL) hasInstalled;
- (BOOL) hasAutoUpdate;
- (BOOL) hasCategory;
- (BOOL) hasAppType;
- (BOOL) hasDownloading;
- (BOOL) hasDownloadPaused;
- (BOOL) hasBytesDownloadRate;
- (BOOL) hasBytesDownloaded;
- (BOOL) hasBytesNeeded;
- (BOOL) hasChanging;
- (BOOL) hasAvailableOnPlatform;
@property (readonly) uint32_t appid;
- (BOOL) favorite;
- (BOOL) installed;
- (BOOL) autoUpdate;
@property (readonly, retain) NSString* category;
@property (readonly, retain) NSString* appType;
- (BOOL) downloading;
- (BOOL) downloadPaused;
@property (readonly) uint32_t bytesDownloadRate;
@property (readonly) uint64_t bytesDownloaded;
@property (readonly) uint64_t bytesNeeded;
- (BOOL) changing;
- (BOOL) availableOnPlatform;

+ (ClientAppInfo*) defaultInstance;
- (ClientAppInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientAppInfo_Builder*) builder;
+ (ClientAppInfo_Builder*) builder;
+ (ClientAppInfo_Builder*) builderWithPrototype:(ClientAppInfo*) prototype;
- (ClientAppInfo_Builder*) toBuilder;

+ (ClientAppInfo*) parseFromData:(NSData*) data;
+ (ClientAppInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientAppInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClientAppInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientAppInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientAppInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientAppInfo_Builder : PBGeneratedMessage_Builder {
@private
  ClientAppInfo* _builderResult;
}

- (ClientAppInfo*) defaultInstance;

- (ClientAppInfo_Builder*) clear;
- (ClientAppInfo_Builder*) clone;

- (ClientAppInfo*) build;
- (ClientAppInfo*) buildPartial;

- (ClientAppInfo_Builder*) mergeFrom:(ClientAppInfo*) other;
- (ClientAppInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientAppInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAppid;
- (uint32_t) appid;
- (ClientAppInfo_Builder*) setAppid:(uint32_t) value;
- (ClientAppInfo_Builder*) clearAppid;

- (BOOL) hasFavorite;
- (BOOL) favorite;
- (ClientAppInfo_Builder*) setFavorite:(BOOL) value;
- (ClientAppInfo_Builder*) clearFavorite;

- (BOOL) hasInstalled;
- (BOOL) installed;
- (ClientAppInfo_Builder*) setInstalled:(BOOL) value;
- (ClientAppInfo_Builder*) clearInstalled;

- (BOOL) hasAutoUpdate;
- (BOOL) autoUpdate;
- (ClientAppInfo_Builder*) setAutoUpdate:(BOOL) value;
- (ClientAppInfo_Builder*) clearAutoUpdate;

- (BOOL) hasCategory;
- (NSString*) category;
- (ClientAppInfo_Builder*) setCategory:(NSString*) value;
- (ClientAppInfo_Builder*) clearCategory;

- (BOOL) hasAppType;
- (NSString*) appType;
- (ClientAppInfo_Builder*) setAppType:(NSString*) value;
- (ClientAppInfo_Builder*) clearAppType;

- (BOOL) hasDownloading;
- (BOOL) downloading;
- (ClientAppInfo_Builder*) setDownloading:(BOOL) value;
- (ClientAppInfo_Builder*) clearDownloading;

- (BOOL) hasDownloadPaused;
- (BOOL) downloadPaused;
- (ClientAppInfo_Builder*) setDownloadPaused:(BOOL) value;
- (ClientAppInfo_Builder*) clearDownloadPaused;

- (BOOL) hasBytesDownloadRate;
- (uint32_t) bytesDownloadRate;
- (ClientAppInfo_Builder*) setBytesDownloadRate:(uint32_t) value;
- (ClientAppInfo_Builder*) clearBytesDownloadRate;

- (BOOL) hasBytesDownloaded;
- (uint64_t) bytesDownloaded;
- (ClientAppInfo_Builder*) setBytesDownloaded:(uint64_t) value;
- (ClientAppInfo_Builder*) clearBytesDownloaded;

- (BOOL) hasBytesNeeded;
- (uint64_t) bytesNeeded;
- (ClientAppInfo_Builder*) setBytesNeeded:(uint64_t) value;
- (ClientAppInfo_Builder*) clearBytesNeeded;

- (BOOL) hasChanging;
- (BOOL) changing;
- (ClientAppInfo_Builder*) setChanging:(BOOL) value;
- (ClientAppInfo_Builder*) clearChanging;

- (BOOL) hasAvailableOnPlatform;
- (BOOL) availableOnPlatform;
- (ClientAppInfo_Builder*) setAvailableOnPlatform:(BOOL) value;
- (ClientAppInfo_Builder*) clearAvailableOnPlatform;
@end

