// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Descriptor.pb.h"

@class CCDDBAppDetailCommon;
@class CCDDBAppDetailCommon_Builder;
@class CMsgAppRights;
@class CMsgAppRights_Builder;
@class CMsgAuthTicket;
@class CMsgAuthTicket_Builder;
@class CMsgMulti;
@class CMsgMulti_Builder;
@class CMsgProtoBufHeader;
@class CMsgProtoBufHeader_Builder;
@class PBDescriptorProto;
@class PBDescriptorProto_Builder;
@class PBDescriptorProto_ExtensionRange;
@class PBDescriptorProto_ExtensionRange_Builder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProto_Builder;
@class PBEnumOptions;
@class PBEnumOptions_Builder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProto_Builder;
@class PBEnumValueOptions;
@class PBEnumValueOptions_Builder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProto_Builder;
@class PBFieldOptions;
@class PBFieldOptions_Builder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProto_Builder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSet_Builder;
@class PBFileOptions;
@class PBFileOptions_Builder;
@class PBMessageOptions;
@class PBMessageOptions_Builder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProto_Builder;
@class PBMethodOptions;
@class PBMethodOptions_Builder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProto_Builder;
@class PBServiceOptions;
@class PBServiceOptions_Builder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfo_Builder;
@class PBSourceCodeInfo_Location;
@class PBSourceCodeInfo_Location_Builder;
@class PBUninterpretedOption;
@class PBUninterpretedOption_Builder;
@class PBUninterpretedOption_NamePart;
@class PBUninterpretedOption_NamePart_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface SteammessagesBaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) msgpoolSoftLimit;
+ (id<PBExtensionField>) msgpoolHardLimit;
@end

@interface CMsgProtoBufHeader : PBGeneratedMessage {
@private
  BOOL hasMessageid_:1;
  BOOL hasClientSessionid_:1;
  BOOL hasEresult_:1;
  BOOL hasTransportError_:1;
  BOOL hasSteamid_:1;
  BOOL hasJobidSource_:1;
  BOOL hasJobidTarget_:1;
  BOOL hasTargetJobName_:1;
  BOOL hasErrorMessage_:1;
  BOOL hasRoutingAppid_:1;
  BOOL hasIp_:1;
  BOOL hasAuthAccountFlags_:1;
  BOOL hasPublisherid_:1;
  uint64_t messageid;
  int32_t clientSessionid;
  int32_t eresult;
  int32_t transportError;
  uint64_t steamid;
  uint64_t jobidSource;
  uint64_t jobidTarget;
  NSString* targetJobName;
  NSString* errorMessage;
  uint32_t routingAppid;
  uint32_t ip;
  uint32_t authAccountFlags;
  uint32_t publisherid;
}
- (BOOL) hasSteamid;
- (BOOL) hasClientSessionid;
- (BOOL) hasRoutingAppid;
- (BOOL) hasJobidSource;
- (BOOL) hasJobidTarget;
- (BOOL) hasTargetJobName;
- (BOOL) hasEresult;
- (BOOL) hasErrorMessage;
- (BOOL) hasIp;
- (BOOL) hasAuthAccountFlags;
- (BOOL) hasTransportError;
- (BOOL) hasMessageid;
- (BOOL) hasPublisherid;
@property (readonly) uint64_t steamid;
@property (readonly) int32_t clientSessionid;
@property (readonly) uint32_t routingAppid;
@property (readonly) uint64_t jobidSource;
@property (readonly) uint64_t jobidTarget;
@property (readonly, retain) NSString* targetJobName;
@property (readonly) int32_t eresult;
@property (readonly, retain) NSString* errorMessage;
@property (readonly) uint32_t ip;
@property (readonly) uint32_t authAccountFlags;
@property (readonly) int32_t transportError;
@property (readonly) uint64_t messageid;
@property (readonly) uint32_t publisherid;

+ (CMsgProtoBufHeader*) defaultInstance;
- (CMsgProtoBufHeader*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgProtoBufHeader_Builder*) builder;
+ (CMsgProtoBufHeader_Builder*) builder;
+ (CMsgProtoBufHeader_Builder*) builderWithPrototype:(CMsgProtoBufHeader*) prototype;
- (CMsgProtoBufHeader_Builder*) toBuilder;

+ (CMsgProtoBufHeader*) parseFromData:(NSData*) data;
+ (CMsgProtoBufHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgProtoBufHeader*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgProtoBufHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgProtoBufHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgProtoBufHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgProtoBufHeader_Builder : PBGeneratedMessage_Builder {
@private
  CMsgProtoBufHeader* result;
}

- (CMsgProtoBufHeader*) defaultInstance;

- (CMsgProtoBufHeader_Builder*) clear;
- (CMsgProtoBufHeader_Builder*) clone;

- (CMsgProtoBufHeader*) build;
- (CMsgProtoBufHeader*) buildPartial;

- (CMsgProtoBufHeader_Builder*) mergeFrom:(CMsgProtoBufHeader*) other;
- (CMsgProtoBufHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgProtoBufHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSteamid;
- (uint64_t) steamid;
- (CMsgProtoBufHeader_Builder*) setSteamid:(uint64_t) value;
- (CMsgProtoBufHeader_Builder*) clearSteamid;

- (BOOL) hasClientSessionid;
- (int32_t) clientSessionid;
- (CMsgProtoBufHeader_Builder*) setClientSessionid:(int32_t) value;
- (CMsgProtoBufHeader_Builder*) clearClientSessionid;

- (BOOL) hasRoutingAppid;
- (uint32_t) routingAppid;
- (CMsgProtoBufHeader_Builder*) setRoutingAppid:(uint32_t) value;
- (CMsgProtoBufHeader_Builder*) clearRoutingAppid;

- (BOOL) hasJobidSource;
- (uint64_t) jobidSource;
- (CMsgProtoBufHeader_Builder*) setJobidSource:(uint64_t) value;
- (CMsgProtoBufHeader_Builder*) clearJobidSource;

- (BOOL) hasJobidTarget;
- (uint64_t) jobidTarget;
- (CMsgProtoBufHeader_Builder*) setJobidTarget:(uint64_t) value;
- (CMsgProtoBufHeader_Builder*) clearJobidTarget;

- (BOOL) hasTargetJobName;
- (NSString*) targetJobName;
- (CMsgProtoBufHeader_Builder*) setTargetJobName:(NSString*) value;
- (CMsgProtoBufHeader_Builder*) clearTargetJobName;

- (BOOL) hasEresult;
- (int32_t) eresult;
- (CMsgProtoBufHeader_Builder*) setEresult:(int32_t) value;
- (CMsgProtoBufHeader_Builder*) clearEresult;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (CMsgProtoBufHeader_Builder*) setErrorMessage:(NSString*) value;
- (CMsgProtoBufHeader_Builder*) clearErrorMessage;

- (BOOL) hasIp;
- (uint32_t) ip;
- (CMsgProtoBufHeader_Builder*) setIp:(uint32_t) value;
- (CMsgProtoBufHeader_Builder*) clearIp;

- (BOOL) hasAuthAccountFlags;
- (uint32_t) authAccountFlags;
- (CMsgProtoBufHeader_Builder*) setAuthAccountFlags:(uint32_t) value;
- (CMsgProtoBufHeader_Builder*) clearAuthAccountFlags;

- (BOOL) hasTransportError;
- (int32_t) transportError;
- (CMsgProtoBufHeader_Builder*) setTransportError:(int32_t) value;
- (CMsgProtoBufHeader_Builder*) clearTransportError;

- (BOOL) hasMessageid;
- (uint64_t) messageid;
- (CMsgProtoBufHeader_Builder*) setMessageid:(uint64_t) value;
- (CMsgProtoBufHeader_Builder*) clearMessageid;

- (BOOL) hasPublisherid;
- (uint32_t) publisherid;
- (CMsgProtoBufHeader_Builder*) setPublisherid:(uint32_t) value;
- (CMsgProtoBufHeader_Builder*) clearPublisherid;
@end

@interface CMsgMulti : PBGeneratedMessage {
@private
  BOOL hasMessageBody_:1;
  BOOL hasSizeUnzipped_:1;
  NSData* messageBody;
  uint32_t sizeUnzipped;
}
- (BOOL) hasSizeUnzipped;
- (BOOL) hasMessageBody;
@property (readonly) uint32_t sizeUnzipped;
@property (readonly, retain) NSData* messageBody;

+ (CMsgMulti*) defaultInstance;
- (CMsgMulti*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgMulti_Builder*) builder;
+ (CMsgMulti_Builder*) builder;
+ (CMsgMulti_Builder*) builderWithPrototype:(CMsgMulti*) prototype;
- (CMsgMulti_Builder*) toBuilder;

+ (CMsgMulti*) parseFromData:(NSData*) data;
+ (CMsgMulti*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMulti*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgMulti*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMulti*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgMulti*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgMulti_Builder : PBGeneratedMessage_Builder {
@private
  CMsgMulti* result;
}

- (CMsgMulti*) defaultInstance;

- (CMsgMulti_Builder*) clear;
- (CMsgMulti_Builder*) clone;

- (CMsgMulti*) build;
- (CMsgMulti*) buildPartial;

- (CMsgMulti_Builder*) mergeFrom:(CMsgMulti*) other;
- (CMsgMulti_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgMulti_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSizeUnzipped;
- (uint32_t) sizeUnzipped;
- (CMsgMulti_Builder*) setSizeUnzipped:(uint32_t) value;
- (CMsgMulti_Builder*) clearSizeUnzipped;

- (BOOL) hasMessageBody;
- (NSData*) messageBody;
- (CMsgMulti_Builder*) setMessageBody:(NSData*) value;
- (CMsgMulti_Builder*) clearMessageBody;
@end

@interface CMsgAuthTicket : PBGeneratedMessage {
@private
  BOOL hasSteamid_:1;
  BOOL hasGameid_:1;
  BOOL hasTicket_:1;
  BOOL hasEstate_:1;
  BOOL hasEresult_:1;
  BOOL hasHSteamPipe_:1;
  BOOL hasTicketCrc_:1;
  uint64_t steamid;
  uint64_t gameid;
  NSData* ticket;
  uint32_t estate;
  uint32_t eresult;
  uint32_t hSteamPipe;
  uint32_t ticketCrc;
}
- (BOOL) hasEstate;
- (BOOL) hasEresult;
- (BOOL) hasSteamid;
- (BOOL) hasGameid;
- (BOOL) hasHSteamPipe;
- (BOOL) hasTicketCrc;
- (BOOL) hasTicket;
@property (readonly) uint32_t estate;
@property (readonly) uint32_t eresult;
@property (readonly) uint64_t steamid;
@property (readonly) uint64_t gameid;
@property (readonly) uint32_t hSteamPipe;
@property (readonly) uint32_t ticketCrc;
@property (readonly, retain) NSData* ticket;

+ (CMsgAuthTicket*) defaultInstance;
- (CMsgAuthTicket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgAuthTicket_Builder*) builder;
+ (CMsgAuthTicket_Builder*) builder;
+ (CMsgAuthTicket_Builder*) builderWithPrototype:(CMsgAuthTicket*) prototype;
- (CMsgAuthTicket_Builder*) toBuilder;

+ (CMsgAuthTicket*) parseFromData:(NSData*) data;
+ (CMsgAuthTicket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAuthTicket*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgAuthTicket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAuthTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgAuthTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgAuthTicket_Builder : PBGeneratedMessage_Builder {
@private
  CMsgAuthTicket* result;
}

- (CMsgAuthTicket*) defaultInstance;

- (CMsgAuthTicket_Builder*) clear;
- (CMsgAuthTicket_Builder*) clone;

- (CMsgAuthTicket*) build;
- (CMsgAuthTicket*) buildPartial;

- (CMsgAuthTicket_Builder*) mergeFrom:(CMsgAuthTicket*) other;
- (CMsgAuthTicket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgAuthTicket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEstate;
- (uint32_t) estate;
- (CMsgAuthTicket_Builder*) setEstate:(uint32_t) value;
- (CMsgAuthTicket_Builder*) clearEstate;

- (BOOL) hasEresult;
- (uint32_t) eresult;
- (CMsgAuthTicket_Builder*) setEresult:(uint32_t) value;
- (CMsgAuthTicket_Builder*) clearEresult;

- (BOOL) hasSteamid;
- (uint64_t) steamid;
- (CMsgAuthTicket_Builder*) setSteamid:(uint64_t) value;
- (CMsgAuthTicket_Builder*) clearSteamid;

- (BOOL) hasGameid;
- (uint64_t) gameid;
- (CMsgAuthTicket_Builder*) setGameid:(uint64_t) value;
- (CMsgAuthTicket_Builder*) clearGameid;

- (BOOL) hasHSteamPipe;
- (uint32_t) hSteamPipe;
- (CMsgAuthTicket_Builder*) setHSteamPipe:(uint32_t) value;
- (CMsgAuthTicket_Builder*) clearHSteamPipe;

- (BOOL) hasTicketCrc;
- (uint32_t) ticketCrc;
- (CMsgAuthTicket_Builder*) setTicketCrc:(uint32_t) value;
- (CMsgAuthTicket_Builder*) clearTicketCrc;

- (BOOL) hasTicket;
- (NSData*) ticket;
- (CMsgAuthTicket_Builder*) setTicket:(NSData*) value;
- (CMsgAuthTicket_Builder*) clearTicket;
@end

@interface CCDDBAppDetailCommon : PBGeneratedMessage {
@private
  BOOL hasTool_:1;
  BOOL hasDemo_:1;
  BOOL hasMedia_:1;
  BOOL hasCommunityVisibleStats_:1;
  BOOL hasName_:1;
  BOOL hasIcon_:1;
  BOOL hasLogo_:1;
  BOOL hasLogoSmall_:1;
  BOOL hasFriendlyName_:1;
  BOOL hasPropagation_:1;
  BOOL hasAppid_:1;
  BOOL tool_:1;
  BOOL demo_:1;
  BOOL media_:1;
  BOOL communityVisibleStats_:1;
  NSString* name;
  NSString* icon;
  NSString* logo;
  NSString* logoSmall;
  NSString* friendlyName;
  NSString* propagation;
  uint32_t appid;
}
- (BOOL) hasAppid;
- (BOOL) hasName;
- (BOOL) hasIcon;
- (BOOL) hasLogo;
- (BOOL) hasLogoSmall;
- (BOOL) hasTool;
- (BOOL) hasDemo;
- (BOOL) hasMedia;
- (BOOL) hasCommunityVisibleStats;
- (BOOL) hasFriendlyName;
- (BOOL) hasPropagation;
@property (readonly) uint32_t appid;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* icon;
@property (readonly, retain) NSString* logo;
@property (readonly, retain) NSString* logoSmall;
- (BOOL) tool;
- (BOOL) demo;
- (BOOL) media;
- (BOOL) communityVisibleStats;
@property (readonly, retain) NSString* friendlyName;
@property (readonly, retain) NSString* propagation;

+ (CCDDBAppDetailCommon*) defaultInstance;
- (CCDDBAppDetailCommon*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CCDDBAppDetailCommon_Builder*) builder;
+ (CCDDBAppDetailCommon_Builder*) builder;
+ (CCDDBAppDetailCommon_Builder*) builderWithPrototype:(CCDDBAppDetailCommon*) prototype;
- (CCDDBAppDetailCommon_Builder*) toBuilder;

+ (CCDDBAppDetailCommon*) parseFromData:(NSData*) data;
+ (CCDDBAppDetailCommon*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CCDDBAppDetailCommon*) parseFromInputStream:(NSInputStream*) input;
+ (CCDDBAppDetailCommon*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CCDDBAppDetailCommon*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CCDDBAppDetailCommon*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CCDDBAppDetailCommon_Builder : PBGeneratedMessage_Builder {
@private
  CCDDBAppDetailCommon* result;
}

- (CCDDBAppDetailCommon*) defaultInstance;

- (CCDDBAppDetailCommon_Builder*) clear;
- (CCDDBAppDetailCommon_Builder*) clone;

- (CCDDBAppDetailCommon*) build;
- (CCDDBAppDetailCommon*) buildPartial;

- (CCDDBAppDetailCommon_Builder*) mergeFrom:(CCDDBAppDetailCommon*) other;
- (CCDDBAppDetailCommon_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CCDDBAppDetailCommon_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAppid;
- (uint32_t) appid;
- (CCDDBAppDetailCommon_Builder*) setAppid:(uint32_t) value;
- (CCDDBAppDetailCommon_Builder*) clearAppid;

- (BOOL) hasName;
- (NSString*) name;
- (CCDDBAppDetailCommon_Builder*) setName:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearName;

- (BOOL) hasIcon;
- (NSString*) icon;
- (CCDDBAppDetailCommon_Builder*) setIcon:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearIcon;

- (BOOL) hasLogo;
- (NSString*) logo;
- (CCDDBAppDetailCommon_Builder*) setLogo:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearLogo;

- (BOOL) hasLogoSmall;
- (NSString*) logoSmall;
- (CCDDBAppDetailCommon_Builder*) setLogoSmall:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearLogoSmall;

- (BOOL) hasTool;
- (BOOL) tool;
- (CCDDBAppDetailCommon_Builder*) setTool:(BOOL) value;
- (CCDDBAppDetailCommon_Builder*) clearTool;

- (BOOL) hasDemo;
- (BOOL) demo;
- (CCDDBAppDetailCommon_Builder*) setDemo:(BOOL) value;
- (CCDDBAppDetailCommon_Builder*) clearDemo;

- (BOOL) hasMedia;
- (BOOL) media;
- (CCDDBAppDetailCommon_Builder*) setMedia:(BOOL) value;
- (CCDDBAppDetailCommon_Builder*) clearMedia;

- (BOOL) hasCommunityVisibleStats;
- (BOOL) communityVisibleStats;
- (CCDDBAppDetailCommon_Builder*) setCommunityVisibleStats:(BOOL) value;
- (CCDDBAppDetailCommon_Builder*) clearCommunityVisibleStats;

- (BOOL) hasFriendlyName;
- (NSString*) friendlyName;
- (CCDDBAppDetailCommon_Builder*) setFriendlyName:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearFriendlyName;

- (BOOL) hasPropagation;
- (NSString*) propagation;
- (CCDDBAppDetailCommon_Builder*) setPropagation:(NSString*) value;
- (CCDDBAppDetailCommon_Builder*) clearPropagation;
@end

@interface CMsgAppRights : PBGeneratedMessage {
@private
  BOOL hasEditInfo_:1;
  BOOL hasPublish_:1;
  BOOL hasViewErrorData_:1;
  BOOL hasDownload_:1;
  BOOL hasUploadCdkeys_:1;
  BOOL hasGenerateCdkeys_:1;
  BOOL hasViewFinancials_:1;
  BOOL hasManageCeg_:1;
  BOOL hasManageSigning_:1;
  BOOL hasManageCdkeys_:1;
  BOOL hasEditMarketing_:1;
  BOOL hasEconomySupport_:1;
  BOOL hasEconomySupportSupervisor_:1;
  BOOL editInfo_:1;
  BOOL publish_:1;
  BOOL viewErrorData_:1;
  BOOL download_:1;
  BOOL uploadCdkeys_:1;
  BOOL generateCdkeys_:1;
  BOOL viewFinancials_:1;
  BOOL manageCeg_:1;
  BOOL manageSigning_:1;
  BOOL manageCdkeys_:1;
  BOOL editMarketing_:1;
  BOOL economySupport_:1;
  BOOL economySupportSupervisor_:1;
}
- (BOOL) hasEditInfo;
- (BOOL) hasPublish;
- (BOOL) hasViewErrorData;
- (BOOL) hasDownload;
- (BOOL) hasUploadCdkeys;
- (BOOL) hasGenerateCdkeys;
- (BOOL) hasViewFinancials;
- (BOOL) hasManageCeg;
- (BOOL) hasManageSigning;
- (BOOL) hasManageCdkeys;
- (BOOL) hasEditMarketing;
- (BOOL) hasEconomySupport;
- (BOOL) hasEconomySupportSupervisor;
- (BOOL) editInfo;
- (BOOL) publish;
- (BOOL) viewErrorData;
- (BOOL) download;
- (BOOL) uploadCdkeys;
- (BOOL) generateCdkeys;
- (BOOL) viewFinancials;
- (BOOL) manageCeg;
- (BOOL) manageSigning;
- (BOOL) manageCdkeys;
- (BOOL) editMarketing;
- (BOOL) economySupport;
- (BOOL) economySupportSupervisor;

+ (CMsgAppRights*) defaultInstance;
- (CMsgAppRights*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgAppRights_Builder*) builder;
+ (CMsgAppRights_Builder*) builder;
+ (CMsgAppRights_Builder*) builderWithPrototype:(CMsgAppRights*) prototype;
- (CMsgAppRights_Builder*) toBuilder;

+ (CMsgAppRights*) parseFromData:(NSData*) data;
+ (CMsgAppRights*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAppRights*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgAppRights*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAppRights*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgAppRights*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgAppRights_Builder : PBGeneratedMessage_Builder {
@private
  CMsgAppRights* result;
}

- (CMsgAppRights*) defaultInstance;

- (CMsgAppRights_Builder*) clear;
- (CMsgAppRights_Builder*) clone;

- (CMsgAppRights*) build;
- (CMsgAppRights*) buildPartial;

- (CMsgAppRights_Builder*) mergeFrom:(CMsgAppRights*) other;
- (CMsgAppRights_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgAppRights_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEditInfo;
- (BOOL) editInfo;
- (CMsgAppRights_Builder*) setEditInfo:(BOOL) value;
- (CMsgAppRights_Builder*) clearEditInfo;

- (BOOL) hasPublish;
- (BOOL) publish;
- (CMsgAppRights_Builder*) setPublish:(BOOL) value;
- (CMsgAppRights_Builder*) clearPublish;

- (BOOL) hasViewErrorData;
- (BOOL) viewErrorData;
- (CMsgAppRights_Builder*) setViewErrorData:(BOOL) value;
- (CMsgAppRights_Builder*) clearViewErrorData;

- (BOOL) hasDownload;
- (BOOL) download;
- (CMsgAppRights_Builder*) setDownload:(BOOL) value;
- (CMsgAppRights_Builder*) clearDownload;

- (BOOL) hasUploadCdkeys;
- (BOOL) uploadCdkeys;
- (CMsgAppRights_Builder*) setUploadCdkeys:(BOOL) value;
- (CMsgAppRights_Builder*) clearUploadCdkeys;

- (BOOL) hasGenerateCdkeys;
- (BOOL) generateCdkeys;
- (CMsgAppRights_Builder*) setGenerateCdkeys:(BOOL) value;
- (CMsgAppRights_Builder*) clearGenerateCdkeys;

- (BOOL) hasViewFinancials;
- (BOOL) viewFinancials;
- (CMsgAppRights_Builder*) setViewFinancials:(BOOL) value;
- (CMsgAppRights_Builder*) clearViewFinancials;

- (BOOL) hasManageCeg;
- (BOOL) manageCeg;
- (CMsgAppRights_Builder*) setManageCeg:(BOOL) value;
- (CMsgAppRights_Builder*) clearManageCeg;

- (BOOL) hasManageSigning;
- (BOOL) manageSigning;
- (CMsgAppRights_Builder*) setManageSigning:(BOOL) value;
- (CMsgAppRights_Builder*) clearManageSigning;

- (BOOL) hasManageCdkeys;
- (BOOL) manageCdkeys;
- (CMsgAppRights_Builder*) setManageCdkeys:(BOOL) value;
- (CMsgAppRights_Builder*) clearManageCdkeys;

- (BOOL) hasEditMarketing;
- (BOOL) editMarketing;
- (CMsgAppRights_Builder*) setEditMarketing:(BOOL) value;
- (CMsgAppRights_Builder*) clearEditMarketing;

- (BOOL) hasEconomySupport;
- (BOOL) economySupport;
- (CMsgAppRights_Builder*) setEconomySupport:(BOOL) value;
- (CMsgAppRights_Builder*) clearEconomySupport;

- (BOOL) hasEconomySupportSupervisor;
- (BOOL) economySupportSupervisor;
- (CMsgAppRights_Builder*) setEconomySupportSupervisor:(BOOL) value;
- (CMsgAppRights_Builder*) clearEconomySupportSupervisor;
@end

