// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class EncryptedAppTicket;
@class EncryptedAppTicket_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface EncryptedAppTicketRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface EncryptedAppTicket : PBGeneratedMessage {
@private
  BOOL hasEncryptedTicket_:1;
  BOOL hasTicketVersionNo_:1;
  BOOL hasCrcEncryptedticket_:1;
  BOOL hasCbEncrypteduserdata_:1;
  BOOL hasCbEncryptedAppownershipticket_:1;
  NSData* encryptedTicket;
  uint32_t ticketVersionNo;
  uint32_t crcEncryptedticket;
  uint32_t cbEncrypteduserdata;
  uint32_t cbEncryptedAppownershipticket;
}
- (BOOL) hasTicketVersionNo;
- (BOOL) hasCrcEncryptedticket;
- (BOOL) hasCbEncrypteduserdata;
- (BOOL) hasCbEncryptedAppownershipticket;
- (BOOL) hasEncryptedTicket;
@property (readonly) uint32_t ticketVersionNo;
@property (readonly) uint32_t crcEncryptedticket;
@property (readonly) uint32_t cbEncrypteduserdata;
@property (readonly) uint32_t cbEncryptedAppownershipticket;
@property (readonly, retain) NSData* encryptedTicket;

+ (EncryptedAppTicket*) defaultInstance;
- (EncryptedAppTicket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EncryptedAppTicket_Builder*) builder;
+ (EncryptedAppTicket_Builder*) builder;
+ (EncryptedAppTicket_Builder*) builderWithPrototype:(EncryptedAppTicket*) prototype;
- (EncryptedAppTicket_Builder*) toBuilder;

+ (EncryptedAppTicket*) parseFromData:(NSData*) data;
+ (EncryptedAppTicket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EncryptedAppTicket*) parseFromInputStream:(NSInputStream*) input;
+ (EncryptedAppTicket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EncryptedAppTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EncryptedAppTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EncryptedAppTicket_Builder : PBGeneratedMessage_Builder {
@private
  EncryptedAppTicket* result;
}

- (EncryptedAppTicket*) defaultInstance;

- (EncryptedAppTicket_Builder*) clear;
- (EncryptedAppTicket_Builder*) clone;

- (EncryptedAppTicket*) build;
- (EncryptedAppTicket*) buildPartial;

- (EncryptedAppTicket_Builder*) mergeFrom:(EncryptedAppTicket*) other;
- (EncryptedAppTicket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EncryptedAppTicket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTicketVersionNo;
- (uint32_t) ticketVersionNo;
- (EncryptedAppTicket_Builder*) setTicketVersionNo:(uint32_t) value;
- (EncryptedAppTicket_Builder*) clearTicketVersionNo;

- (BOOL) hasCrcEncryptedticket;
- (uint32_t) crcEncryptedticket;
- (EncryptedAppTicket_Builder*) setCrcEncryptedticket:(uint32_t) value;
- (EncryptedAppTicket_Builder*) clearCrcEncryptedticket;

- (BOOL) hasCbEncrypteduserdata;
- (uint32_t) cbEncrypteduserdata;
- (EncryptedAppTicket_Builder*) setCbEncrypteduserdata:(uint32_t) value;
- (EncryptedAppTicket_Builder*) clearCbEncrypteduserdata;

- (BOOL) hasCbEncryptedAppownershipticket;
- (uint32_t) cbEncryptedAppownershipticket;
- (EncryptedAppTicket_Builder*) setCbEncryptedAppownershipticket:(uint32_t) value;
- (EncryptedAppTicket_Builder*) clearCbEncryptedAppownershipticket;

- (BOOL) hasEncryptedTicket;
- (NSData*) encryptedTicket;
- (EncryptedAppTicket_Builder*) setEncryptedTicket:(NSData*) value;
- (EncryptedAppTicket_Builder*) clearEncryptedTicket;
@end

